{ "global": {
    "database_url": "sqlite:///enduro_tracker.db", # still to adjust in alembic.ini
    "debug_mode": true,
    "api_host": "0.0.0.0",
    "api_port": 5000,
    "allowed_origins": ["*"],
    "timezone": "Africa/Johannesburg", #"UTC", # this is the default timezone for the application
    "category": ["Professional", "Open", "Junior"]
  },
  "example": "example_text"
}
